import type { ContentLang, Lang } from "./types";

/** A ready-made forms list: the verb, its meaning (Dutch and English) and its forms per column. */
export interface VerbSet {
  id: string;
  lang: ContentLang;
  name: Record<Lang, string>;
  subject: Record<Lang, string>;
  columns: string[];
  verbs: { verb: string; nl: string; en: string; forms: string[] }[];
}

const FR = ["je", "tu", "il / elle / on", "nous", "vous", "ils / elles"];
const DE = ["ich", "du", "er / sie / es", "wir", "ihr", "sie / Sie"];
const ES = ["yo", "tú", "él / ella / usted", "nosotros", "vosotros", "ellos / ellas / ustedes"];

const v = (verb: string, nl: string, en: string, forms: string) => ({ verb, nl, en, forms: forms.split(",").map((f) => f.trim()) });

export const VERB_SETS: VerbSet[] = [
  {
    id: "en-irregular",
    lang: "en",
    name: { nl: "Engels: onregelmatige werkwoorden", en: "English: irregular verbs" },
    subject: { nl: "Engels", en: "English" },
    columns: ["past simple", "past participle"],
    verbs: [
      v("be", "zijn", "be", "was / were, been"),
      v("become", "worden", "become", "became, become"),
      v("begin", "beginnen", "begin", "began, begun"),
      v("break", "breken", "break", "broke, broken"),
      v("bring", "brengen", "bring", "brought, brought"),
      v("build", "bouwen", "build", "built, built"),
      v("buy", "kopen", "buy", "bought, bought"),
      v("catch", "vangen", "catch", "caught, caught"),
      v("choose", "kiezen", "choose", "chose, chosen"),
      v("come", "komen", "come", "came, come"),
      v("cost", "kosten", "cost", "cost, cost"),
      v("cut", "snijden", "cut", "cut, cut"),
      v("do", "doen", "do", "did, done"),
      v("draw", "tekenen", "draw", "drew, drawn"),
      v("drink", "drinken", "drink", "drank, drunk"),
      v("drive", "rijden (auto)", "drive", "drove, driven"),
      v("eat", "eten", "eat", "ate, eaten"),
      v("fall", "vallen", "fall", "fell, fallen"),
      v("feel", "voelen", "feel", "felt, felt"),
      v("find", "vinden", "find", "found, found"),
      v("fly", "vliegen", "fly", "flew, flown"),
      v("forget", "vergeten", "forget", "forgot, forgotten"),
      v("get", "krijgen", "get", "got, got / gotten"),
      v("give", "geven", "give", "gave, given"),
      v("go", "gaan", "go", "went, gone"),
      v("grow", "groeien", "grow", "grew, grown"),
      v("have", "hebben", "have", "had, had"),
      v("hear", "horen", "hear", "heard, heard"),
      v("hold", "vasthouden", "hold", "held, held"),
      v("keep", "houden", "keep", "kept, kept"),
      v("know", "weten / kennen", "know", "knew, known"),
      v("leave", "vertrekken / verlaten", "leave", "left, left"),
      v("lose", "verliezen", "lose", "lost, lost"),
      v("make", "maken", "make", "made, made"),
      v("meet", "ontmoeten", "meet", "met, met"),
      v("pay", "betalen", "pay", "paid, paid"),
      v("put", "zetten / leggen", "put", "put, put"),
      v("read", "lezen", "read", "read, read"),
      v("ride", "rijden (fiets, paard)", "ride", "rode, ridden"),
      v("run", "rennen", "run", "ran, run"),
      v("say", "zeggen", "say", "said, said"),
      v("see", "zien", "see", "saw, seen"),
      v("sell", "verkopen", "sell", "sold, sold"),
      v("send", "sturen", "send", "sent, sent"),
      v("sing", "zingen", "sing", "sang, sung"),
      v("sit", "zitten", "sit", "sat, sat"),
      v("sleep", "slapen", "sleep", "slept, slept"),
      v("speak", "spreken", "speak", "spoke, spoken"),
      v("spend", "uitgeven / doorbrengen", "spend", "spent, spent"),
      v("stand", "staan", "stand", "stood, stood"),
      v("swim", "zwemmen", "swim", "swam, swum"),
      v("take", "nemen", "take", "took, taken"),
      v("teach", "lesgeven", "teach", "taught, taught"),
      v("tell", "vertellen", "tell", "told, told"),
      v("think", "denken", "think", "thought, thought"),
      v("throw", "gooien", "throw", "threw, thrown"),
      v("understand", "begrijpen", "understand", "understood, understood"),
      v("wake", "wakker worden", "wake", "woke, woken"),
      v("wear", "dragen (kleding)", "wear", "wore, worn"),
      v("win", "winnen", "win", "won, won"),
      v("write", "schrijven", "write", "wrote, written"),
    ],
  },
  {
    id: "fr-present",
    lang: "fr",
    name: { nl: "Frans: présent", en: "French: présent" },
    subject: { nl: "Frans", en: "French" },
    columns: FR,
    verbs: [
      v("être", "zijn", "to be", "suis, es, est, sommes, êtes, sont"),
      v("avoir", "hebben", "to have", "ai, as, a, avons, avez, ont"),
      v("aller", "gaan", "to go", "vais, vas, va, allons, allez, vont"),
      v("faire", "doen / maken", "to do / to make", "fais, fais, fait, faisons, faites, font"),
      v("prendre", "nemen", "to take", "prends, prends, prend, prenons, prenez, prennent"),
      v("venir", "komen", "to come", "viens, viens, vient, venons, venez, viennent"),
      v("pouvoir", "kunnen", "can", "peux, peux, peut, pouvons, pouvez, peuvent"),
      v("vouloir", "willen", "to want", "veux, veux, veut, voulons, voulez, veulent"),
      v("devoir", "moeten", "must", "dois, dois, doit, devons, devez, doivent"),
      v("savoir", "weten", "to know", "sais, sais, sait, savons, savez, savent"),
      v("dire", "zeggen", "to say", "dis, dis, dit, disons, dites, disent"),
      v("voir", "zien", "to see", "vois, vois, voit, voyons, voyez, voient"),
      v("mettre", "zetten / leggen", "to put", "mets, mets, met, mettons, mettez, mettent"),
      v("parler", "praten / spreken", "to speak", "parle, parles, parle, parlons, parlez, parlent"),
      v("finir", "eindigen", "to finish", "finis, finis, finit, finissons, finissez, finissent"),
      v("vendre", "verkopen", "to sell", "vends, vends, vend, vendons, vendez, vendent"),
    ],
  },
  {
    id: "de-praesens",
    lang: "de",
    name: { nl: "Duits: Präsens", en: "German: Präsens" },
    subject: { nl: "Duits", en: "German" },
    columns: DE,
    verbs: [
      v("sein", "zijn", "to be", "bin, bist, ist, sind, seid, sind"),
      v("haben", "hebben", "to have", "habe, hast, hat, haben, habt, haben"),
      v("werden", "worden", "to become", "werde, wirst, wird, werden, werdet, werden"),
      v("können", "kunnen", "can", "kann, kannst, kann, können, könnt, können"),
      v("müssen", "moeten", "must", "muss, musst, muss, müssen, müsst, müssen"),
      v("wollen", "willen", "to want", "will, willst, will, wollen, wollt, wollen"),
      v("dürfen", "mogen", "may", "darf, darfst, darf, dürfen, dürft, dürfen"),
      v("sollen", "moeten (van een ander)", "should", "soll, sollst, soll, sollen, sollt, sollen"),
      v("mögen", "lusten / leuk vinden", "to like", "mag, magst, mag, mögen, mögt, mögen"),
      v("wissen", "weten", "to know", "weiß, weißt, weiß, wissen, wisst, wissen"),
      v("fahren", "rijden / varen", "to drive", "fahre, fährst, fährt, fahren, fahrt, fahren"),
      v("lesen", "lezen", "to read", "lese, liest, liest, lesen, lest, lesen"),
      v("sprechen", "spreken", "to speak", "spreche, sprichst, spricht, sprechen, sprecht, sprechen"),
      v("nehmen", "nemen", "to take", "nehme, nimmst, nimmt, nehmen, nehmt, nehmen"),
      v("geben", "geven", "to give", "gebe, gibst, gibt, geben, gebt, geben"),
      v("sehen", "zien", "to see", "sehe, siehst, sieht, sehen, seht, sehen"),
      v("essen", "eten", "to eat", "esse, isst, isst, essen, esst, essen"),
      v("schlafen", "slapen", "to sleep", "schlafe, schläfst, schläft, schlafen, schlaft, schlafen"),
      v("laufen", "lopen", "to run", "laufe, läufst, läuft, laufen, lauft, laufen"),
      v("machen", "maken / doen", "to make / to do", "mache, machst, macht, machen, macht, machen"),
      v("arbeiten", "werken", "to work", "arbeite, arbeitest, arbeitet, arbeiten, arbeitet, arbeiten"),
    ],
  },
  {
    id: "es-presente",
    lang: "es",
    name: { nl: "Spaans: presente", en: "Spanish: presente" },
    subject: { nl: "Spaans", en: "Spanish" },
    columns: ES,
    verbs: [
      v("ser", "zijn (blijvend)", "to be (lasting)", "soy, eres, es, somos, sois, son"),
      v("estar", "zijn (tijdelijk, plaats)", "to be (temporary, place)", "estoy, estás, está, estamos, estáis, están"),
      v("tener", "hebben", "to have", "tengo, tienes, tiene, tenemos, tenéis, tienen"),
      v("ir", "gaan", "to go", "voy, vas, va, vamos, vais, van"),
      v("hacer", "doen / maken", "to do / to make", "hago, haces, hace, hacemos, hacéis, hacen"),
      v("poder", "kunnen", "can", "puedo, puedes, puede, podemos, podéis, pueden"),
      v("querer", "willen", "to want", "quiero, quieres, quiere, queremos, queréis, quieren"),
      v("decir", "zeggen", "to say", "digo, dices, dice, decimos, decís, dicen"),
      v("venir", "komen", "to come", "vengo, vienes, viene, venimos, venís, vienen"),
      v("salir", "uitgaan / vertrekken", "to go out", "salgo, sales, sale, salimos, salís, salen"),
      v("hablar", "praten / spreken", "to speak", "hablo, hablas, habla, hablamos, habláis, hablan"),
      v("comer", "eten", "to eat", "como, comes, come, comemos, coméis, comen"),
      v("vivir", "wonen / leven", "to live", "vivo, vives, vive, vivimos, vivís, viven"),
    ],
  },
];
