import "@fontsource/familjen-grotesk/latin-400.css";
import "@fontsource/familjen-grotesk/latin-600.css";
import "@fontsource/familjen-grotesk/latin-700.css";
import "@fontsource/source-serif-4/latin-400.css";
import "@fontsource/source-serif-4/latin-600.css";
import "@fontsource/ibm-plex-mono/latin-400.css";
import "@fontsource/ibm-plex-mono/latin-500.css";
import "@fontsource/reenie-beanie/latin-400.css";
import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/card.css";
import { mount } from "svelte";
import App from "./App.svelte";
import { app } from "./lib/app.svelte";
import { initPwa } from "./lib/pwa.svelte";

const target = document.getElementById("app");
if (!target) throw new Error("Missing #app");
mount(App, { target });
void app.init();
initPwa();
